# Copyright Â© 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

[Writable]
LogLevel = 'INFO'

[Service]
ClientMonitor = '15s'
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 48095
ReadMaxLimit = 100
StartupMsg = 'This microservice exposes a CRUD interface for an inventory of items in a Automated Checkout'
RequestTimeout = '30s'
MaxRequestSize = 0

[Registry]
Host = "localhost"
Port = 8500
Type = 'consul'

[Trigger]
Type="http"

[ApplicationSettings]
