---
# Copyright Â© 2020 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

version: "3.4"

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  Registry_Host: edgex-core-consul
  Clients_CoreData_Host: edgex-core-data
  Clients_Data_Host: edgex-core-data
  Clients_Notifications_Host: edgex-support-notifications
  Clients_Metadata_Host: edgex-core-metadata
  Clients_Command_Host: edgex-core-command
  Clients_Scheduler_Host: edgex-support-scheduler
  Clients_RulesEngine_Host: edgex-kuiper
  Clients_VirtualDevice_Host: edgex-device-virtual
  Databases_Primary_Host: edgex-redis
  Logging_EnableRemote: "false"

x-logging: &logging
  logging:
    options: { max-file: "5", max-size: 100m }

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:

services:
  consul:
    image: edgexfoundry/docker-edgex-consul:1.2.0
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    volumes:
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
    restart: always
    ports:
      - "127.0.0.1:8400:8400"
      - "127.0.0.1:8500:8500"
    environment:
      - EDGEX_DB=redis
      - EDGEX_SECURE=false

  redis:
    image: redis:5.0.8-alpine
    ports:
      - "127.0.0.1:6379:6379"
    container_name: edgex-redis
    hostname: edgex-redis
    environment:
      <<: *common-variables
    volumes:
      - db-data:/data:z

  notifications:
    image: edgexfoundry/docker-support-notifications-go:1.2.0
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    environment:
      <<: *common-variables
      Service_Host: edgex-support-notifications
      Smtp_Username: "your-email@site.com"
      Smtp_Password: "SomePassword00000!"
      Smtp_Sender: "your-email@site.com"
      Smtp_Subject: "Automated Checkout Maintenance Alert"
    depends_on:
      - consul
      - redis
    restart: always
    ports:
      - "127.0.0.1:48060:48060"

  metadata:
    image: edgexfoundry/docker-core-metadata-go:1.2.0
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    environment:
      <<: *common-variables
      Service_Host: edgex-core-metadata
      Notifications_Sender: edgex-core-metadata
    depends_on:
      - consul
      - redis
      - notifications
    restart: always
    ports:
      - "127.0.0.1:48081:48081"

  data:
    image: edgexfoundry/docker-core-data-go:1.2.0
    container_name: edgex-core-data
    hostname: edgex-core-data
    environment:
      <<: *common-variables
      Service_Host: edgex-core-data
    depends_on:
      - consul
      - redis
      - metadata
    restart: always
    ports:
      - "127.0.0.1:48080:48080"
      - "127.0.0.1:5563:5563"

  command:
    image: edgexfoundry/docker-core-command-go:1.2.0
    container_name: edgex-core-command
    hostname: edgex-core-command
    environment:
      <<: *common-variables
      Service_Host: edgex-core-command
    depends_on:
      - consul
      - redis
      - metadata
    restart: always
    ports:
      - "127.0.0.1:48082:48082"

  #################################################################
  # Automated Checkout Microservices
  #################################################################

  device-mqtt:
    user: "2000:2000"
    image: edgexfoundry/docker-device-mqtt-go:1.2.0
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    environment:
      <<: *common-variables
      Service_Host: edgex-device-mqtt
      Service_Port: 48100
    <<: *logging
    volumes:
      - ./res/device-mqtt:/res:ro
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48100:48100"

  ds-card-reader:
    user: "2000:2000"
    image: "automated-checkout/ds-card-reader:dev"
    container_name: automated-checkout_ds-card-reader
    environment:
      <<: *common-variables
      Service_Host: ds-card-reader
    <<: *logging
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48098:48098"

  ds-controller-board:
    user: "2000:2000"
    image: "automated-checkout/ds-controller-board:dev"
    container_name: automated-checkout_ds-controller-board
    environment:
      <<: *common-variables
      Service_Host: ds-controller-board
    <<: *logging
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48097:48097"

  ds-cv-inference:
    user: "2000:2000"
    image: automated-checkout/ds-cv-inference:dev
    container_name: automated-checkout_ds-cv-inference
    ipc: none
    command: ["/go/src/ds-cv-inference/images","mqtt-broker:1883","0.85","/go/src/ds-cv-inference/skumapping.json"]
    depends_on:
      - mqtt-broker
    ports:
      - "127.0.0.1:9005:9005"

  as-controller-board-status:
    user: "2000:2000"
    image: "automated-checkout/as-controller-board-status:dev"
    container_name: automated-checkout_as-controller-board-status
    environment:
      <<: *common-variables
      Service_Host: as-controller-board-status
      MessageBus_SubscribeHost_Host: edgex-core-data
      ApplicationSettings_MQTTEndpoint: "http://edgex-core-command:48082/api/v1/device/name/Inference-MQTT-device/command/inferenceDoorStatus"
      ApplicationSettings_NotificationHost: "http://edgex-support-notifications:48060/api/v1/notification"
      ApplicationSettings_SubscriptionHost: "http://edgex-support-notifications:48060/api/v1/subscription"
      ApplicationSettings_VendingEndpoint: "http://as-vending:48099/boardStatus"
    <<: *logging
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48094:48094"

  as-vending:
    user: "2000:2000"
    image: "automated-checkout/as-vending:dev"
    container_name: automated-checkout_as-vending
    environment:
      <<: *common-variables
      Service_Host: as-vending
      MessageBus_SubscribeHost_Host: edgex-core-data
      ApplicationSettings_AuthenticationEndpoint: http://ms-authentication:48096/authentication
      ApplicationSettings_DeviceControllerBoarddisplayReset: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/displayReset
      ApplicationSettings_DeviceControllerBoarddisplayRow0: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/displayRow0
      ApplicationSettings_DeviceControllerBoarddisplayRow1: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/displayRow1
      ApplicationSettings_DeviceControllerBoarddisplayRow2: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/displayRow2
      ApplicationSettings_DeviceControllerBoarddisplayRow3: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/displayRow3
      ApplicationSettings_DeviceControllerBoardLock1: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/lock1
      ApplicationSettings_DeviceControllerBoardLock2: http://edgex-core-command:48082/api/v1/device/name/ds-controller-board/command/lock2
      ApplicationSettings_InferenceDoorStatus: http://edgex-core-command:48082/api/v1/device/name/Inference-MQTT-device/command/inferenceDoorStatus
      ApplicationSettings_InferenceHeartbeat: http://edgex-core-command:48082/api/v1/device/name/Inference-MQTT-device/command/inferenceHeartbeat
      ApplicationSettings_InventoryAuditLogService: http://ms-inventory:48095/auditlog
      ApplicationSettings_InventoryService: http://ms-inventory:48095/inventory/delta
      ApplicationSettings_LedgerService: http://ms-ledger:48093/ledger
    <<: *logging
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48099:48099"

  mqtt-broker:
    image: eclipse-mosquitto:1.6.3
    container_name: mqtt-broker
    volumes:
      - ./res/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    <<: *logging
    depends_on:
      - data
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"

  ms-authentication:
    user: "2000:2000"
    image: "automated-checkout/ms-authentication:dev"
    container_name: automated-checkout_ms-authentication
    environment:
      <<: *common-variables
      Service_Host: ms-authentication
      MessageBus_SubscribeHost_Host: edgex-core-data
    <<: *logging
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48096:48096"

  ms-inventory:
    user: "2000:2000"
    image: "automated-checkout/ms-inventory:dev"
    container_name: automated-checkout_ms-inventory
    ipc: none
    depends_on:
      - data
      - command
    environment:
      <<: *common-variables
      Service_Host: ms-inventory
      MessageBus_SubscribeHost_Host: edgex-core-data
    <<: *logging
    restart: always
    ports:
      - "127.0.0.1:48095:48095"

  ms-ledger:
    user: "2000:2000"
    image: "automated-checkout/ms-ledger:dev"
    container_name: automated-checkout_ms-ledger
    environment:
      <<: *common-variables
      Service_Host: ms-ledger
      MessageBus_SubscribeHost_Host: edgex-core-data
      ApplicationSettings_InventoryEndpoint: http://ms-inventory:48095/inventory
    <<: *logging
    depends_on:
      - data
      - command
    restart: always
    ipc: none
    ports:
      - "127.0.0.1:48093:48093"

networks:
  default:
