# Copyright Â© 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.DB]
        path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 48099
StartupMsg = 'This is an Application Service which reads card inputs and publishes lock status back to message bus'
RequestTimeout = '30s'
MaxRequestSize = 0
ServerBindAddr = ""
MaxResultCount = 0

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "mqtt"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "none"
    ClientId ="as-vending"
    Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "5" # Seconds
    SkipCertVerify = "false"

[Clients]
  # Used for version check on start-up
  # Also used for DeviceService, DeviceProfile and Device clients
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

  [Clients.core-command]
  Protocol = "http"
  Host = "localhost"
  Port = 59882

[Vending]
  AuthenticationEndpoint = "http://localhost:48096/authentication"
  ControllerBoardDisplayResetCmd = "displayReset"
  ControllerBoardDisplayRow0Cmd = "displayRow0"
  ControllerBoardDisplayRow1Cmd = "displayRow1"
  ControllerBoardDisplayRow2Cmd = "displayRow2"
  ControllerBoardDisplayRow3Cmd = "displayRow3"
  ControllerBoardLock1Cmd = "lock1"
  ControllerBoardLock2Cmd = "lock2"
  # DeviceNames should be comma separated, with no spaces
  DeviceNames   = "card-reader,Inference-MQTT-device"
  DoorCloseStateTimeoutDuration = "20s"
  DoorOpenStateTimeoutDuration = "15s"
  InferenceDoorStatusCmd = "inferenceDoorStatus"
  InferenceHeartbeatCmd = "inferenceHeartbeat"
  InferenceTimeoutDuration = "20s"
  InventoryAuditLogService = "http://localhost:48095/auditlog"
  InventoryService = "http://localhost:48095/inventory/delta"
  LCDRowLength = 19
  LedgerService = "http://localhost:48093/ledger"